name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Or your preferred runner

    steps:
      - uses: actions/checkout@v3 # Checkout the code

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin # Or your preferred JDK distribution
          java-version: 23
      
      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main
        with:
          kotlin-version: '2.0.21'
      
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew
        working-directory: ./AlgoKotlin

      - name: Build and Test with Gradle
        working-directory: ./AlgoKotlin
        run: ./gradlew build test